### PR TITLE
Py test (NO MERGE CONFLICT)

### PR DESCRIPTION
**Pull request by ccho-0508**
Added tests folder containing all the tests

To run tests that need credentials check README file (Includes instructions for running tests/creating reports)
tests for RepoCommunicator and BookingBuilder --> Takes long to test - needs to be deleted safely after each test so sleep() is used to make sure its completely gone (Wait 5 secs).
report.html file is the output

### CODE REVIEW

**Comment by bobby-palko** [comment]
now there's a merge conflict on the imports!

**Comment by ccho-0508** [comment]
brb going to cry

**Comment by ccho-0508** [comment]
Forgot to note : TraverseSite_test will probably fail the first test since the string isn't updated - could already be booked / too late to book

**Review by bobby-palko — APPROVED** [review]
Thanks for getting all these tests written! I know it's a pain. I don't think we need to wrap tests in `try/except` blocks. If our test causing a complete crash in the program, then we should probably fix the program lol. If we're testing that an exception was handled, we can assert that the error message is what we expect (or however we're handling the exception).

lgtm 👍🏻  I'm gonna toss some mocks in there and such so we don't need user creds to test too

**Pull request merged**
